// lib/structure/data.ts — Static definitions for all 6 narrative structures

export type StructureTypeId =
  | 'three_act' | 'save_the_cat' | 'dan_harmon'
  | 'vogler' | 'john_truby' | 'eight_sequence';

export interface StructureStage {
  id: string;
  order: number;
  color: string;
  colorLight: string;
  name: { az: string; en: string; ru: string };
  description: { az: string; en: string; ru: string };
  keyQuestion: { az: string; en: string; ru: string };
  arcStart?: number;
  arcEnd?: number;
}

export interface StructureDefinition {
  id: StructureTypeId;
  visualType: 'columns' | 'circle' | 'timeline' | 'journey' | 'vertical' | 'eight_cols';
  difficulty: 1 | 2 | 3;
  filterTags: string[];
  name: { az: string; en: string; ru: string };
  shortDesc: { az: string; en: string; ru: string };
  fullDesc: { az: string; en: string; ru: string };
  bestFor: { az: string; en: string; ru: string };
  filmExamples: { title: string; year: number; why: string }[];
  stages: StructureStage[];
}

// ─── 1. THREE ACT ───

export const THREE_ACT: StructureDefinition = {
  id: 'three_act', visualType: 'columns', difficulty: 1,
  filterTags: ['feature', 'tv', 'independent', 'commercial', 'beginner'],
  name: { az: '3 Pərdə Quruluşu', en: 'Three-Act Structure', ru: 'Трёхактная Структура' },
  shortDesc: { az: 'Aristoteldən bu günə bütün quruluşların ortaq dili.', en: 'The common language of all structures from Aristotle to today.', ru: 'Общий язык всех структур от Аристотеля до сегодня.' },
  fullDesc: { az: 'Ən sadə görünən amma ən güclü quruluşdur. Digər bütün quruluşlar bunun üzərində inşa olunub.', en: 'Appears simplest but most powerful. All other structures build on top of 3 Acts.', ru: 'Самая простая но мощная. Все структуры строятся поверх неё.' },
  bestFor: { az: 'Hər format. Xüsusilə ilk ssenarini yazanlar üçün.', en: 'Every format. Especially for writing your first screenplay.', ru: 'Каждый формат. Особенно для первого сценария.' },
  filmExamples: [
    { title: 'Casablanca', year: 1942, why: 'Klassik 3 pərdə — hər aşama mükəmməl tarazlıqda' },
    { title: 'The Godfather', year: 1972, why: "Michael'in dönüşümü 3 pərdə boyunca izlənir" },
    { title: 'A Separation', year: 2011, why: 'Bağımsız sinemada 3 pərdə sadeliyi' },
  ],
  stages: [
    { id: 'act1', order: 1, color: '#2D2B6B', colorLight: '#EEF0FF',
      name: { az: '1-ci Pərdə — Quruluş', en: 'Act 1 — Setup', ru: 'Акт 1 — Экспозиция' },
      description: { az: 'Personajlar, dünya və əsas çatışma tanıdılır.', en: 'Characters, world, and central conflict are introduced.', ru: 'Представляются персонажи, мир и конфликт.' },
      keyQuestion: { az: 'Qəhrəman hansı dünyada yaşayır və nə onu dəyişdirəcək?', en: 'What world does the hero live in and what will change them?', ru: 'В каком мире живёт герой и что его изменит?' } },
    { id: 'act2a', order: 2, color: '#E67E22', colorLight: '#FEF3E7',
      name: { az: '2-ci Pərdə A — Çatışma', en: 'Act 2A — Confrontation', ru: 'Акт 2А — Конфронтация' },
      description: { az: 'Qəhrəman yeni dünyada mübarizə edir, ilk uğurlar və məğlubiyyətlər.', en: 'The hero struggles in the new world, first successes and failures.', ru: 'Герой борется в новом мире.' },
      keyQuestion: { az: 'Qəhrəmanın yeni dünyada ehtiyacı nədir — istədiyi nədir?', en: 'What does the hero need in the new world — vs what they think they want?', ru: 'Что нужно герою — против того, что он хочет?' } },
    { id: 'midpoint', order: 3, color: '#C0392B', colorLight: '#FDEDEC',
      name: { az: 'Orta Nöqtə', en: 'Midpoint', ru: 'Середина' },
      description: { az: 'Saxta qələbə ya da saxta məğlubiyyət. Riskler yüksəlir.', en: 'False victory or false defeat. Stakes rise.', ru: 'Ложная победа или поражение. Ставки растут.' },
      keyQuestion: { az: 'Qəhrəman özünü güclü mü, zəif mi hiss edir — hansı yanlışdır?', en: 'Does the hero feel strong or weak — which one is false?', ru: 'Герой чувствует себя сильным или слабым — что ложно?' } },
    { id: 'act2b', order: 4, color: '#8E44AD', colorLight: '#F5EEF8',
      name: { az: '2-ci Pərdə B — Qaranlıq', en: 'Act 2B — Darkness', ru: 'Акт 2Б — Тьма' },
      description: { az: 'Hər şey pisləşir. Köməkçilər dağılır. Qəhrəman tək qalır.', en: 'Everything worsens. Helpers scatter. Hero is alone.', ru: 'Всё ухудшается. Герой один.' },
      keyQuestion: { az: 'Qəhrəman ən aşağı noktaya çatanda hansı həqiqəti görəcək?', en: 'What truth will the hero see at their lowest point?', ru: 'Какую истину увидит герой в низшей точке?' } },
    { id: 'act3', order: 5, color: '#27AE60', colorLight: '#E9F7EF',
      name: { az: '3-cü Pərdə — Həll', en: 'Act 3 — Resolution', ru: 'Акт 3 — Развязка' },
      description: { az: 'Qəhrəman çevrilir. Son üzləşmə. Yeni dünya qurulur.', en: 'The hero transforms. Final confrontation. New world built.', ru: 'Герой трансформируется. Финальная конфронтация.' },
      keyQuestion: { az: 'Qəhrəman başlanğıcdakı dünyasına qayıdanda nə dəyişib?', en: 'When the hero returns to their original world, what has changed?', ru: 'Когда герой возвращается, что изменилось?' } },
  ],
};

// ─── 2. SAVE THE CAT ───

export const SAVE_THE_CAT: StructureDefinition = {
  id: 'save_the_cat', visualType: 'timeline', difficulty: 2,
  filterTags: ['feature', 'commercial', 'action', 'comedy', 'thriller'],
  name: { az: 'Save the Cat — 15 Mərhələ', en: 'Save the Cat — 15 Beats', ru: 'Save the Cat — 15 Битов' },
  shortDesc: { az: "Blake Snyder'in Hollywood şablonu.", en: "Blake Snyder's Hollywood template.", ru: 'Голливудский шаблон Блейка Снайдера.' },
  fullDesc: { az: 'Ticari filmlər üçün ən dəqiq xəritə. 15 beat sırası ilə hekayə quruluşu.', en: 'The most precise map for commercial films. Story structure via 15 sequential beats.', ru: 'Самая точная карта для коммерческих фильмов. 15 последовательных битов.' },
  bestFor: { az: 'Hollywood filmi, komediya, triller, aksiyon.', en: 'Hollywood films, comedy, thriller, action.', ru: 'Голливудское кино, комедия, триллер, экшн.' },
  filmExamples: [
    { title: 'The Dark Knight', year: 2008, why: 'Midpoint — Joker bankayı soyur, stakes maksimum' },
    { title: 'Toy Story', year: 1995, why: "All Is Lost — Woody çöp kutusunda, Dark Night mükemmel" },
    { title: 'When Harry Met Sally', year: 1989, why: 'B Story — dostluğun aşka dönüşü tema ile bütünleşiyor' },
  ],
  stages: [
    { id: 'opening_image', order: 1, color: '#1B4F72', colorLight: '#D6EAF8',
      name: { az: 'Açılış Görüntüsü', en: 'Opening Image', ru: 'Открывающий Образ' },
      description: { az: 'Filmin tonu, personajın başlanğıc vəziyyəti. Final Image\'ın əksi.', en: "Film's tone and character's starting state. Must mirror opposite Final Image.", ru: 'Тон и начальное состояние. Зеркало Финального Образа.' },
      keyQuestion: { az: 'Bu dünya necə görünür? Son görüntünün tam əksi nədir?', en: 'What does this world look like? What is the exact opposite at the end?', ru: 'Как выглядит мир? Что является противоположностью в конце?' } },
    { id: 'theme_stated', order: 2, color: '#1A5276', colorLight: '#EAF2FF',
      name: { az: 'Tema Bildirişi', en: 'Theme Stated', ru: 'Заявленная Тема' },
      description: { az: 'Filmin əsas teması — çox vaxt başqa biri tərəfindən söylənir.', en: "Film's central theme — usually said by someone else.", ru: 'Центральная тема — обычно произносится кем-то другим.' },
      keyQuestion: { az: 'Filmin əxlaqi sualı nədir?', en: "What is the film's moral question?", ru: 'Каков моральный вопрос фильма?' } },
    { id: 'setup', order: 3, color: '#2E86C1', colorLight: '#EAF4FB',
      name: { az: 'Quruluş', en: 'Set-Up', ru: 'Установка' },
      description: { az: 'Personajlar, dünya, nöqsan, daxili çatışma.', en: 'Characters, world, flaw, internal conflict.', ru: 'Персонажи, мир, изъян, внутренний конфликт.' },
      keyQuestion: { az: 'Qəhrəmanın əsas nöqsanı nədir?', en: "What is the hero's fundamental flaw?", ru: 'В чём главный изъян героя?' } },
    { id: 'catalyst', order: 4, color: '#E67E22', colorLight: '#FEF3E7',
      name: { az: 'Katalizator', en: 'Catalyst', ru: 'Катализатор' },
      description: { az: 'Həyatı dəyişdirən hadisə. Geri dönüş yoxdur.', en: 'The life-changing event. No going back.', ru: 'Событие, меняющее жизнь. Обратного пути нет.' },
      keyQuestion: { az: 'Qəhrəmanı hərəkətə keçməyə məcbur edən nədir? Niyə indi?', en: 'What forces the hero into action? Why NOW?', ru: 'Что вынуждает действовать? Почему СЕЙЧАС?' } },
    { id: 'debate', order: 5, color: '#F39C12', colorLight: '#FEF9E7',
      name: { az: 'Mübahisə', en: 'Debate', ru: 'Дебаты' },
      description: { az: '"Getməliyəmmi?" Qəhrəman tərəddüd edir.', en: '"Should I go?" The hero hesitates.', ru: '"Идти ли?" Герой колеблется.' },
      keyQuestion: { az: 'Qəhrəmanın ən böyük qorkusu nədir?', en: "What is the hero's greatest fear?", ru: 'Каков величайший страх героя?' } },
    { id: 'break_into_two', order: 6, color: '#D35400', colorLight: '#FBEEE6',
      name: { az: '2-ci Pərdəyə Keçid', en: 'Break Into Two', ru: 'Переход во Второй Акт' },
      description: { az: 'Qəhrəman qərar verir, yeni dünyaya adım atır.', en: 'The hero decides and steps into the new world.', ru: 'Герой решает и шагает в новый мир.' },
      keyQuestion: { az: 'Geri dönüş artıq niyə mümkün deyil?', en: 'Why is going back no longer possible?', ru: 'Почему возврат больше невозможен?' } },
    { id: 'b_story', order: 7, color: '#8E44AD', colorLight: '#F5EEF8',
      name: { az: 'B Hekayəsi', en: 'B Story', ru: 'История Б' },
      description: { az: 'İkincil hekayə — çox vaxt sevgi xətti. A hekayəsinin temasını daşıyır.', en: 'Secondary story — often love line. Carries the A story theme.', ru: 'Вторичная история. Несёт тему основной.' },
      keyQuestion: { az: 'Bu ikincil münasibət qəhrəmanın dəyişməsinə necə kömək edir?', en: 'How does this secondary relationship help the hero change?', ru: 'Как вторичные отношения помогают герою измениться?' } },
    { id: 'fun_and_games', order: 8, color: '#27AE60', colorLight: '#E9F7EF',
      name: { az: 'Əyləncə və Oyunlar', en: 'Fun and Games', ru: 'Веселье и Игры' },
      description: { az: "Filmin 'vədi'nin yerinə gətirildiyi yer.", en: "Where the film's 'promise' is delivered. Trailers are cut from here.", ru: "Место, где выполняется 'обещание' фильма." },
      keyQuestion: { az: 'Bu filmin "əyləncəsi" nədir?', en: "What is the film's 'fun'? What does the audience want to see?", ru: "В чём 'веселье' этого фильма?" } },
    { id: 'midpoint', order: 9, color: '#C0392B', colorLight: '#FDEDEC',
      name: { az: 'Orta Nöqtə', en: 'Midpoint', ru: 'Средняя Точка' },
      description: { az: 'Saxta qələbə ya da saxta məğlubiyyət. Riskler yüksəlir.', en: 'False victory or false defeat. Stakes rise dramatically.', ru: 'Ложная победа или поражение. Ставки резко возрастают.' },
      keyQuestion: { az: 'Qəhrəman özünü aldanırmı?', en: 'Is the hero deceiving themselves?', ru: 'Герой обманывает себя?' } },
    { id: 'bad_guys_close_in', order: 10, color: '#922B21', colorLight: '#FDEDEC',
      name: { az: 'Pis Adamlar Yaxınlaşır', en: 'Bad Guys Close In', ru: 'Злодеи Приближаются' },
      description: { az: 'Xarici düşmən yaxınlaşır. Komanda dağılır.', en: 'External enemy closes in. Team breaks apart.', ru: 'Внешний враг приближается. Команда распадается.' },
      keyQuestion: { az: 'Qəhrəmanın müttəfiqini nə dağıdır?', en: "What breaks the hero's ally — external pressure or the hero's own flaw?", ru: 'Что разрушает союзника?' } },
    { id: 'all_is_lost', order: 11, color: '#6C3483', colorLight: '#F5EEF8',
      name: { az: 'Hər Şey İtirildi', en: 'All Is Lost', ru: 'Всё Потеряно' },
      description: { az: "Qəhrəmanın ən aşağı nöqtəsi. 'Ölüm' simvolu olmalıdır.", en: "Hero's lowest point. There must be a symbol of 'death' here.", ru: "Низшая точка. Символ 'смерти'." },
      keyQuestion: { az: "Qəhrəmanın 'köhnə özü' nə üçün ölür?", en: "Why does the hero's 'old self' die here?", ru: "Почему 'старое я' героя умирает?" } },
    { id: 'dark_night', order: 12, color: '#2C3E50', colorLight: '#EAF0FB',
      name: { az: 'Ruhun Qaranlıq Gecəsi', en: 'Dark Night of the Soul', ru: 'Тёмная Ночь Души' },
      description: { az: '"Niyə davam edim?" Qəhrəman B hekayəsindəki cavabı tapır.', en: '"Why continue?" Hero finds answer in B story.', ru: '"Зачем продолжать?" Ответ в истории Б.' },
      keyQuestion: { az: 'Qəhrəman bu anda nə anlayır?', en: "What does the hero understand that begins to answer the film's question?", ru: 'Что герой понимает?' } },
    { id: 'break_into_three', order: 13, color: '#1D8348', colorLight: '#E9F7EF',
      name: { az: '3-cü Pərdəyə Keçid', en: 'Break Into Three', ru: 'Переход в Третий Акт' },
      description: { az: 'A+B hekayələri birləşir. Həll tapılır.', en: 'A+B stories merge. Solution found.', ru: 'Истории А+Б объединяются.' },
      keyQuestion: { az: 'Qəhrəman son dəfə nəyi seçir?', en: "What does the hero choose one final time?", ru: 'Что герой выбирает в последний раз?' } },
    { id: 'finale', order: 14, color: '#E67E22', colorLight: '#FEF3E7',
      name: { az: 'Final', en: 'Finale', ru: 'Финал' },
      description: { az: 'Plan icra edilir. Köhnə dünya yıxılır, yeni dünya qurulur.', en: 'Plan executes. Old world torn down, new world built.', ru: 'План выполняется. Старый мир рушится, строится новый.' },
      keyQuestion: { az: 'Qəhrəman hansı köhnə versiyasını məğlub edir?', en: 'Which old version of themselves does the hero defeat?', ru: 'Какую старую версию себя побеждает герой?' } },
    { id: 'final_image', order: 15, color: '#1B4F72', colorLight: '#D6EAF8',
      name: { az: 'Son Görüntü', en: 'Final Image', ru: 'Финальный Образ' },
      description: { az: 'Opening Image\'ın əksi. Dönüşüm vizual olaraq sübut edilir.', en: 'Mirror of Opening Image. Transformation visually proven.', ru: 'Зеркало Открывающего Образа. Трансформация доказана.' },
      keyQuestion: { az: 'Son görüntü birinci görüntünün nəyini dəyişdirir?', en: 'What does the final image change about the first image?', ru: 'Что финальный образ меняет в первом?' } },
  ],
};

// ─── 3. DAN HARMON STORY CIRCLE ───

export const DAN_HARMON: StructureDefinition = {
  id: 'dan_harmon', visualType: 'circle', difficulty: 2,
  filterTags: ['feature', 'tv', 'short', 'comedy', 'drama'],
  name: { az: 'Dan Harmon Hekayə Dairəsi', en: 'Dan Harmon Story Circle', ru: 'Круг Истории Дэна Хармона' },
  shortDesc: { az: 'Hər hekayə bir dairədir. 8 addım — universaldır.', en: 'Every story is a circle. 8 steps — universal.', ru: 'Каждая история — круг. 8 шагов — универсально.' },
  fullDesc: { az: "Campbell'ın monomitinin sadələşdirilmiş versiyası. TV seriyaları üçün mükəmməldir.", en: "Simplified Campbell monomyth. Perfect for TV series episodes.", ru: 'Упрощённый мономиф Кэмпбелла. Идеально для ТВ-эпизодов.' },
  bestFor: { az: 'TV seriyaları, qısa film, komediya, drama.', en: 'TV series, short films, comedy, drama.', ru: 'ТВ-сериалы, короткометражки, комедия, драма.' },
  filmExamples: [
    { title: 'Breaking Bad', year: 2008, why: 'Hər epizod mükəmməl Story Circle izləyir' },
    { title: 'Community', year: 2009, why: "Dan Harmon'un öz serialı — hər epizod dairə" },
    { title: 'The Matrix', year: 1999, why: 'Neo\'nun yolçuluğu mükəmməl dairə' },
  ],
  stages: [
    { id: 'you', order: 1, color: '#2D2B6B', colorLight: '#EEF0FF', arcStart: 157.5, arcEnd: 202.5,
      name: { az: 'SƏN — Zona', en: 'YOU — Comfort Zone', ru: 'ТЫ — Зона Комфорта' },
      description: { az: 'Personaj tanış zonada. Status quo.', en: 'Character in their comfort zone. Status quo.', ru: 'Персонаж в зоне комфорта. Статус-кво.' },
      keyQuestion: { az: 'Bu personajın "normal" həyatı nədir?', en: "What is the character's 'normal' life?", ru: "Что такое 'нормальная' жизнь персонажа?" } },
    { id: 'need', order: 2, color: '#8E44AD', colorLight: '#F5EEF8', arcStart: 202.5, arcEnd: 247.5,
      name: { az: 'EHTİYAC — Nəsə istəyir', en: 'NEED — Something', ru: 'НУЖДА — Чего-то хочет' },
      description: { az: 'Bir şeyə ehtiyac duyur ya da istəyir. Dəyişimin toxumu.', en: 'Wants or needs something. The seed of change.', ru: 'Нужно или хочется чего-то. Семя перемен.' },
      keyQuestion: { az: 'Ehtiyac ilə istək arasındakı fərq nədir?', en: 'What is the difference between need and want?', ru: 'В чём разница между потребностью и желанием?' } },
    { id: 'go', order: 3, color: '#E67E22', colorLight: '#FEF3E7', arcStart: 247.5, arcEnd: 292.5,
      name: { az: 'GET — Tanış olmayan yerə', en: 'GO — Unfamiliar Situation', ru: 'УХОД — В незнакомое' },
      description: { az: 'Tanış olmayan bir vəziyyətə girir.', en: 'Enters an unfamiliar situation.', ru: 'Попадает в незнакомую ситуацию.' },
      keyQuestion: { az: 'Zona komfortunu nə məcbur tərk etdirir?', en: 'What forces them to leave their comfort zone?', ru: 'Что вынуждает покинуть зону комфорта?' } },
    { id: 'search', order: 4, color: '#F1C40F', colorLight: '#FEF9E7', arcStart: 292.5, arcEnd: 337.5,
      name: { az: 'AXTAR — Uyğunlaşma', en: 'SEARCH — Adapt', ru: 'ПОИСК — Адаптация' },
      description: { az: 'Yeni vəziyyətə uyğunlaşmağa çalışır.', en: 'Tries to adapt to the new situation.', ru: 'Пытается адаптироваться.' },
      keyQuestion: { az: 'Uyğunlaşma prosesi nəyi öyrədir?', en: 'What does the adaptation process teach?', ru: 'Чему учит процесс адаптации?' } },
    { id: 'find', order: 5, color: '#27AE60', colorLight: '#E9F7EF', arcStart: 337.5, arcEnd: 22.5,
      name: { az: 'TAP — İstədiyini tapır', en: 'FIND — Gets What They Wanted', ru: 'НАХОДКА — Получает желаемое' },
      description: { az: 'Axtardığını tapır — amma qiymət var.', en: 'Finds what they were looking for — but at a cost.', ru: 'Находит искомое — но есть цена.' },
      keyQuestion: { az: 'Tapılan şeyin gizli qiyməti nədir?', en: 'What is the hidden cost of what was found?', ru: 'Какова скрытая цена находки?' } },
    { id: 'take', order: 6, color: '#C0392B', colorLight: '#FDEDEC', arcStart: 22.5, arcEnd: 67.5,
      name: { az: 'Götürmək — Ağır qiymət', en: 'TAKE — Heavy Price', ru: 'ПЛАТА — Тяжёлая цена' },
      description: { az: 'Ağır bir qiymət ödəyir.', en: 'Pays a heavy price.', ru: 'Платит тяжёлую цену.' },
      keyQuestion: { az: 'Qiymət qəhrəmanı necə dəyişdirir?', en: 'How does the price change the hero?', ru: 'Как цена меняет героя?' } },
    { id: 'return', order: 7, color: '#1ABC9C', colorLight: '#E8F8F5', arcStart: 67.5, arcEnd: 112.5,
      name: { az: 'QAYIT — Tanış yerə', en: 'RETURN — Familiar Situation', ru: 'ВОЗВРАЩЕНИЕ — В знакомое' },
      description: { az: 'Tanış vəziyyətə qayıdır.', en: 'Returns to the familiar situation.', ru: 'Возвращается в знакомую ситуацию.' },
      keyQuestion: { az: 'Qayıdış niyə əvvəlkindən fərqlidir?', en: 'Why is the return different from before?', ru: 'Почему возвращение отличается от прежнего?' } },
    { id: 'change', order: 8, color: '#2D2B6B', colorLight: '#EEF0FF', arcStart: 112.5, arcEnd: 157.5,
      name: { az: 'DƏYİŞ — Dəyişmiş qayıdır', en: 'CHANGE — Having Changed', ru: 'ИЗМЕНЕНИЕ — Вернулся изменившимся' },
      description: { az: 'Dəyişmiş halda. Yeni tarazlıq.', en: 'Changed state. New equilibrium.', ru: 'Изменённое состояние. Новое равновесие.' },
      keyQuestion: { az: 'Dəyişim nəyi sübut edir?', en: 'What does the change prove?', ru: 'Что доказывает изменение?' } },
  ],
};

// ─── 4. VOGLER HERO'S JOURNEY ───

export const VOGLER: StructureDefinition = {
  id: 'vogler', visualType: 'journey', difficulty: 2,
  filterTags: ['feature', 'fantasy', 'adventure', 'epic', 'mythology'],
  name: { az: 'Vogler Qəhrəmanın Yolçuluğu', en: "Vogler Hero's Journey", ru: 'Путешествие Героя Воглера' },
  shortDesc: { az: 'Campbell\'ın mif quruluşunun Vogler uyarlaması. 12 universal addım.', en: "Vogler's adaptation of Campbell's mythic structure. 12 universal steps.", ru: 'Адаптация Воглером мифической структуры. 12 шагов.' },
  fullDesc: { az: 'Fantezi, macəra və epik hekayələr üçün mükəmməl. Hər addım arxetipal.', en: 'Perfect for fantasy, adventure, and epic stories. Every step is archetypal.', ru: 'Идеально для фэнтези, приключений и эпических историй.' },
  bestFor: { az: 'Fantezi, macəra, epik, mifoloji hekayələr.', en: 'Fantasy, adventure, epic, mythological stories.', ru: 'Фэнтези, приключения, эпические, мифологические истории.' },
  filmExamples: [
    { title: 'Star Wars: A New Hope', year: 1977, why: 'Mükəmməl Vogler xəritəsi — hər addım dəqiq yerindədir' },
    { title: 'The Lion King', year: 1994, why: 'Simba\'nın yolçuluğu — Return of the Elixir güclü' },
    { title: "Harry Potter and the Sorcerer's Stone", year: 2001, why: 'Ordinary World\'dan Special World\'a klassik keçiş' },
  ],
  stages: [
    { id: 'ordinary_world', order: 1, color: '#2D2B6B', colorLight: '#EEF0FF',
      name: { az: 'Adi Dünya', en: 'Ordinary World', ru: 'Обычный Мир' },
      description: { az: 'Qəhrəmanın macəradan əvvəlki dünyası.', en: "The hero's world before the adventure.", ru: 'Мир героя до приключения.' },
      keyQuestion: { az: 'Bu adi dünya qəhrəmanı necə məhdudlaşdırır?', en: 'How does the ordinary world limit the hero?', ru: 'Как обычный мир ограничивает героя?' } },
    { id: 'call_to_adventure', order: 2, color: '#E67E22', colorLight: '#FEF3E7',
      name: { az: 'Macəraya Çağırış', en: 'Call to Adventure', ru: 'Зов Приключений' },
      description: { az: 'Problem, meydan oxuma ya da fırsat.', en: 'A problem or opportunity calls the hero to action.', ru: 'Проблема или возможность зовёт к действию.' },
      keyQuestion: { az: 'Bu çağırış qəhrəmanın taleyini necə dəyişdirir?', en: "How does this call change the hero's fate?", ru: 'Как этот зов меняет судьбу?' } },
    { id: 'refusal_of_call', order: 3, color: '#F39C12', colorLight: '#FEF9E7',
      name: { az: 'Çağırışın Rədd Edilməsi', en: 'Refusal of the Call', ru: 'Отказ от Зова' },
      description: { az: 'Qəhrəman qorxu ya öhdəlik səbəbilə tərəddüd edir.', en: 'The hero hesitates due to fear or obligation.', ru: 'Герой колеблется из-за страха.' },
      keyQuestion: { az: 'Qəhrəmanın rədd etməsinin kökündə hansı qorxu var?', en: "What fear lies at the root of the hero's refusal?", ru: 'Какой страх в основе отказа?' } },
    { id: 'meeting_mentor', order: 4, color: '#8E44AD', colorLight: '#F5EEF8',
      name: { az: 'Mentor ilə Görüşmə', en: 'Meeting the Mentor', ru: 'Встреча с Наставником' },
      description: { az: 'Bilgili yol göstərən. Silah, bilik ya da özgüvən verir.', en: 'A wise guide provides weapons, knowledge, or confidence.', ru: 'Мудрый наставник даёт оружие, знания или уверенность.' },
      keyQuestion: { az: 'Mentor qəhrəmana nəyi verir ki, yolculuq onsuz mümkün olmaz?', en: "What does the mentor give that makes the journey possible?", ru: 'Что даёт наставник для возможности путешествия?' } },
    { id: 'crossing_threshold', order: 5, color: '#C0392B', colorLight: '#FDEDEC',
      name: { az: 'Eşiyin Keçilməsi', en: 'Crossing the First Threshold', ru: 'Пересечение Первого Порога' },
      description: { az: 'Adi dünyadan xüsusi dünyaya keçiş.', en: 'Transition from ordinary to special world. No going back.', ru: 'Переход в особый мир. Обратного пути нет.' },
      keyQuestion: { az: 'Bu keçidlə nə geri bırakılır?', en: 'What is left behind with this crossing?', ru: 'Что остаётся позади?' } },
    { id: 'tests_allies_enemies', order: 6, color: '#27AE60', colorLight: '#E9F7EF',
      name: { az: 'Sınaqlar, Müttəfiqlər, Düşmənlər', en: 'Tests, Allies, Enemies', ru: 'Испытания, Союзники, Враги' },
      description: { az: 'Xüsusi dünyanın qaydaları öyrənilir.', en: 'Special world rules learned. Friends and enemies identified.', ru: 'Правила особого мира. Друзья и враги.' },
      keyQuestion: { az: 'Bu dünyanın qaydası qəhrəmanın güclü cəhətini zəiflikə çevirirmi?', en: "Do the special world's rules turn strength into weakness?", ru: 'Превращают ли правила силу в слабость?' } },
    { id: 'approach_to_cave', order: 7, color: '#D35400', colorLight: '#FBEEE6',
      name: { az: 'Ən Dərin Mağaraya Yaxınlaşma', en: 'Approach to the Inmost Cave', ru: 'Приближение к Заветной Пещере' },
      description: { az: 'Əsas çatışmanın baş verəcəyi yerə yaxınlaşma.', en: 'Approach to where main conflict will occur.', ru: 'Приближение к месту главного конфликта.' },
      keyQuestion: { az: 'Qəhrəmanın ən böyük qorkusu nədir?', en: "What is the hero's greatest fear?", ru: 'Каков величайший страх?' } },
    { id: 'ordeal', order: 8, color: '#922B21', colorLight: '#FDEDEC',
      name: { az: 'Sınaq / Böhran', en: 'Ordeal', ru: 'Испытание / Кризис' },
      description: { az: 'Ölüm-həyat mübarizəsi. Simvolik yenidən doğuş.', en: 'Life or death struggle. Symbolic rebirth.', ru: 'Борьба не на жизнь. Символическое перерождение.' },
      keyQuestion: { az: "Qəhrəmanın 'köhnə özü' nə üçün ölür?", en: "Why does the hero's 'old self' die?", ru: "Почему 'старое я' умирает?" } },
    { id: 'reward', order: 9, color: '#1D8348', colorLight: '#E9F7EF',
      name: { az: 'Mükafat', en: 'Reward (Seizing the Sword)', ru: 'Награда' },
      description: { az: 'Qəhrəman axtardığını tapır — amma qiymət var.', en: "Hero finds what they sought — but there's a price.", ru: 'Герой находит искомое — но есть цена.' },
      keyQuestion: { az: 'Bu mükafat istədiyi mi, ehtiyacı olan mı?', en: 'Is this what the hero wanted or what they needed?', ru: 'Это то, что хотел или что нужно?' } },
    { id: 'road_back', order: 10, color: '#2E86C1', colorLight: '#EAF4FB',
      name: { az: 'Geri Yol', en: 'The Road Back', ru: 'Дорога Назад' },
      description: { az: 'Adi dünyaya qayıtma qərarı.', en: 'Decision to return to ordinary world.', ru: 'Решение вернуться.' },
      keyQuestion: { az: 'Qəhrəman geri qayıtmaq istəyirmi?', en: 'Does the hero want to return?', ru: 'Хочет ли герой вернуться?' } },
    { id: 'resurrection', order: 11, color: '#6C3483', colorLight: '#F5EEF8',
      name: { az: 'Dirilmə', en: 'Resurrection', ru: 'Воскрешение' },
      description: { az: 'Son ölüm-həyat sınağı. Dəyişim sübut edilir.', en: 'Final death-life test. Transformation proven.', ru: 'Финальное испытание. Трансформация доказана.' },
      keyQuestion: { az: 'Qəhrəman dəyişdiyini necə sübut edir?', en: 'How does the hero prove they have changed?', ru: 'Как герой доказывает изменение?' } },
    { id: 'return_with_elixir', order: 12, color: '#1B4F72', colorLight: '#D6EAF8',
      name: { az: 'İksirle Qayıdış', en: 'Return with the Elixir', ru: 'Возвращение с Эликсиром' },
      description: { az: 'Qəhrəman dünyasına xəzinə gətirir.', en: 'The hero brings treasure to their world.', ru: 'Герой приносит сокровище.' },
      keyQuestion: { az: "Qəhrəmanın gətirdiyi 'iksir' dünyasını necə dəyişir?", en: "How does the hero's 'elixir' make their world better?", ru: "Как 'эликсир' делает мир лучше?" } },
  ],
};

// ─── 5. JOHN TRUBY 22 STEPS ───

export const JOHN_TRUBY: StructureDefinition = {
  id: 'john_truby', visualType: 'vertical', difficulty: 3,
  filterTags: ['feature', 'independent', 'drama', 'character_driven', 'advanced'],
  name: { az: 'John Truby — 22 Addım', en: 'John Truby — 22 Steps', ru: 'Джон Труби — 22 Шага' },
  shortDesc: { az: 'Ən kapsamlı sistem. Personaj nöqsanı + əxlaqi arqument + rəqib münasibəti.', en: 'Most comprehensive system. Character flaw + moral argument + opponent.', ru: 'Самая комплексная система. Изъян + моральный аргумент + оппонент.' },
  fullDesc: { az: 'Dərin personaj təhlili üçün. 22 addım ilə hər aspekti əhatə edir.', en: 'For deep character analysis. Covers every aspect in 22 steps.', ru: 'Для глубокого анализа персонажей. 22 шага охватывают всё.' },
  bestFor: { az: 'Bağımsız sinema, drama, personaj dərinliyi istəyən ssenaristlər.', en: 'Independent cinema, drama, character-driven screenwriters.', ru: 'Независимое кино, драма, характерные сценарии.' },
  filmExamples: [
    { title: 'Chinatown', year: 1974, why: "Truby'nin sevdiyi film — moral argument mükemmel" },
    { title: 'The Godfather', year: 1972, why: "Michael'in weakness-to-desire arc'ı 22 adımla izlenir" },
    { title: 'Parasite', year: 2019, why: 'Tematik arqument — hiyerarşi və məkan' },
  ],
  stages: [
    { id: 'self_revelation_need', order: 1, color: '#2D2B6B', colorLight: '#EEF0FF',
      name: { az: 'Özünüifşaat Ehtiyacı', en: 'Self-Revelation Need', ru: 'Потребность в Самораскрытии' },
      description: { az: 'Personajın fərqinə varmadan daşıdığı psixoloji yük.', en: 'The psychological burden the character carries without realizing.', ru: 'Психологический груз, который несёт персонаж не осознавая.' },
      keyQuestion: { az: 'Personajın əsas nöqsanı nədir?', en: "What is the character's fundamental flaw?", ru: 'В чём фундаментальный изъян?' } },
    { id: 'ghost_world', order: 2, color: '#6C3483', colorLight: '#F5EEF8',
      name: { az: 'Keçmiş Travma / Dünya', en: 'Ghost / World', ru: 'Призрак / Мир' },
      description: { az: 'Keçmişdə yaşadığı travma.', en: "Trauma from character's past — shadow over everything.", ru: 'Травма из прошлого — тень всего.' },
      keyQuestion: { az: 'Keçmişdəki bu hadisə indiki hərəkətlərini necə idarə edir?', en: 'How does this past event control present actions?', ru: 'Как прошлое управляет настоящим?' } },
    { id: 'weakness_need', order: 3, color: '#8E44AD', colorLight: '#F5EEF8',
      name: { az: 'Zəiflik və Ehtiyac', en: 'Weakness and Need', ru: 'Слабость и Потребность' },
      description: { az: 'Psixoloji ehtiyac (daxili) + əxlaqi ehtiyac (xarici).', en: 'Psychological need (internal) + moral need (external).', ru: 'Психологическая + моральная потребность.' },
      keyQuestion: { az: 'Psixoloji ilə əxlaqi ehtiyac arasındakı gərginlik nədir?', en: 'What is the tension between psychological and moral need?', ru: 'Какова tension между потребностями?' } },
    { id: 'desire', order: 4, color: '#E67E22', colorLight: '#FEF3E7',
      name: { az: 'İstək', en: 'Desire', ru: 'Желание' },
      description: { az: 'Personajın açıq istəyi.', en: "Character's explicit desire — what they chase.", ru: 'Явное желание — то, что преследует.' },
      keyQuestion: { az: 'İstək ilə ehtiyac niyə çatışır?', en: 'Why does desire conflict with need?', ru: 'Почему желание конфликтует с потребностью?' } },
    { id: 'opponent', order: 5, color: '#C0392B', colorLight: '#FDEDEC',
      name: { az: 'Rəqib', en: 'Opponent', ru: 'Оппонент' },
      description: { az: 'Qəhrəmanla eyni istəyi istəyən, amma fərqli üsulla.', en: "Wants the same as hero but by different means.", ru: 'Хочет того же, но другими методами.' },
      keyQuestion: { az: 'Rəqib qəhrəmanın aynasıdırsa, hansı cəhəti gizlədir?', en: "If the opponent is the hero's mirror, what do they hide?", ru: 'Какой аспект скрывает оппонент?' } },
    { id: 'plan', order: 6, color: '#F39C12', colorLight: '#FEF9E7',
      name: { az: 'Plan', en: 'Plan', ru: 'План' },
      description: { az: 'İstəyə çatmaq üçün strategiya.', en: 'Strategy to reach the desire.', ru: 'Стратегия достижения желаемого.' },
      keyQuestion: { az: 'Planın ən zəif nöqtəsi nədir?', en: "What is the plan's weakest point?", ru: 'Каково слабое место плана?' } },
    { id: 'drive', order: 7, color: '#27AE60', colorLight: '#E9F7EF',
      name: { az: 'Hərəkət', en: 'Drive', ru: 'Движение' },
      description: { az: 'Qəhrəman aktiv şəkildə istəyini izləyir.', en: 'Hero actively pursuing desire.', ru: 'Герой активно преследует желание.' },
      keyQuestion: { az: 'Niyə hərəkətini sürətləndirir?', en: 'Why does the hero accelerate?', ru: 'Почему герой ускоряется?' } },
    { id: 'ally', order: 8, color: '#1ABC9C', colorLight: '#E8F8F5',
      name: { az: 'Müttəfiq', en: 'Ally', ru: 'Союзник' },
      description: { az: 'Dəstəkləyən, amma eyni zamanda sınayan kəs.', en: 'Supports but also tests the hero.', ru: 'Поддерживает, но и испытывает.' },
      keyQuestion: { az: 'Müttəfiq qəhrəmanın hansı körü nöqtəsini görür?', en: "What blind spot does the ally see?", ru: 'Какую слепую зону видит союзник?' } },
    { id: 'fake_ally_opponent', order: 9, color: '#922B21', colorLight: '#FDEDEC',
      name: { az: 'Yalançı Müttəfiq/Rəqib', en: 'Fake Ally Opponent', ru: 'Ложный Союзник/Оппонент' },
      description: { az: 'Qəhrəman onları yanlış qiymətləndirir.', en: 'Hero misjudges them. Major blow later.', ru: 'Герой их неправильно оценивает.' },
      keyQuestion: { az: 'Qəhrəmanı yanıltmaq üçün nəyi gizlədirlər?', en: 'What do they hide to mislead?', ru: 'Что скрывают для обмана?' } },
    { id: 'first_revelation', order: 10, color: '#D35400', colorLight: '#FBEEE6',
      name: { az: 'Birinci Açıqlama', en: 'First Revelation & Decision', ru: 'Первое Откровение и Решение' },
      description: { az: 'Qəhrəman özü haqqında ilk həqiqəti öyrənir.', en: 'Hero learns first truth about themselves.', ru: 'Герой узнаёт первую правду о себе.' },
      keyQuestion: { az: 'Bu açıqlama dünyasının hansı hissəsini alt üst edir?', en: 'Which part of the world does this upend?', ru: 'Какую часть мира переворачивает?' } },
    { id: 'gate_guardian', order: 11, color: '#2E86C1', colorLight: '#EAF4FB',
      name: { az: 'Qapı / Qoruyucu', en: 'Gate, Guardian, Gauntlet', ru: 'Врата, Страж, Испытание' },
      description: { az: 'Sınaq qapısı. Dəyişim üçün son hazırlıq.', en: 'Trial gate. Final preparation for change.', ru: 'Врата испытания. Подготовка к изменению.' },
      keyQuestion: { az: 'Bu sınaqda nəyi sübut etməlidir?', en: 'What must the hero prove?', ru: 'Что должен доказать герой?' } },
    { id: 'revelation_decision', order: 12, color: '#138D75', colorLight: '#E8F8F5',
      name: { az: 'Açıqlama, Qərar', en: 'Revelation & Decision', ru: 'Откровение, Решение' },
      description: { az: 'Orta nöqtə açıqlaması. Daha böyük həqiqət.', en: 'Midpoint revelation. Larger truth, new decision.', ru: 'Откровение средней точки. Более широкая правда.' },
      keyQuestion: { az: 'Bu yeni həqiqət əvvəlki qərarı necə dəyişdirir?', en: 'How does this truth change the earlier decision?', ru: 'Как правда меняет прежнее решение?' } },
    { id: 'audience_revelation', order: 13, color: '#1B4F72', colorLight: '#D6EAF8',
      name: { az: 'Tamaşaçı Açıqlaması', en: 'Audience Revelation', ru: 'Откровение для Аудитории' },
      description: { az: 'Tamaşaçı qəhrəmandan daha çox bilir.', en: 'Audience knows more than hero — tension grows.', ru: 'Аудитория знает больше героя.' },
      keyQuestion: { az: 'Tamaşaçı nə bilir ki, qəhrəman bilmir?', en: "What does audience know that hero doesn't?", ru: 'Что знает аудитория, чего не знает герой?' } },
    { id: 'drive_to_climax', order: 14, color: '#8E44AD', colorLight: '#F5EEF8',
      name: { az: 'Klimaksa Doğru Hərəkət', en: 'Drive to Climax', ru: 'Движение к Кульминации' },
      description: { az: 'Hər şey sürətlənir.', en: 'Everything accelerates toward final point.', ru: 'Всё ускоряется к финальной точке.' },
      keyQuestion: { az: 'Qəhrəmanın planı niyə yetərli deyil?', en: "Why is the hero's plan insufficient?", ru: 'Почему план недостаточен?' } },
    { id: 'attack_by_ally', order: 15, color: '#E74C3C', colorLight: '#FDEDEC',
      name: { az: 'Müttəfiqin Hücumu', en: 'Attack by Ally', ru: 'Атака Союзника' },
      description: { az: 'Ən yaxın müttəfiq tərk edir ya hücum edir.', en: 'Closest ally abandons or attacks. Deepest betrayal.', ru: 'Ближайший союзник предаёт.' },
      keyQuestion: { az: 'Bu xəyanət qəhrəmanın öz nöqsanından mı doğur?', en: "Does this stem from the hero's own flaw?", ru: 'Проистекает ли из изъяна героя?' } },
    { id: 'climax', order: 16, color: '#C0392B', colorLight: '#FDEDEC',
      name: { az: 'Klimaks', en: 'Climax', ru: 'Кульминация' },
      description: { az: 'Son üzləşmə. Bütün xətlər kəsişir.', en: 'Final confrontation. All storylines intersect.', ru: 'Финальная конфронтация. Все линии пересекаются.' },
      keyQuestion: { az: 'Həm daxili, həm xarici düşmənlə necə üzləşir?', en: 'How does the hero face both internal and external enemy?', ru: 'Как сталкивается с обоими врагами?' } },
    { id: 'self_revelation', order: 17, color: '#27AE60', colorLight: '#E9F7EF',
      name: { az: 'Özünüifşaat', en: 'Self-Revelation', ru: 'Самораскрытие' },
      description: { az: 'Dərin həqiqəti görür. Ən emosional an.', en: "Deep truth seen. Film's most emotional moment.", ru: 'Глубокая правда. Самый эмоциональный момент.' },
      keyQuestion: { az: 'Bu məqamda qəhrəman kimdir?', en: 'Who is the hero now?', ru: 'Кто герой теперь?' } },
    { id: 'moral_decision', order: 18, color: '#1D8348', colorLight: '#E9F7EF',
      name: { az: 'Əxlaqi Qərar', en: 'Moral Decision', ru: 'Моральное Решение' },
      description: { az: 'Özünüifşaatdan sonra əxlaqi qərar.', en: "Moral decision after self-revelation.", ru: 'Моральное решение после самораскрытия.' },
      keyQuestion: { az: 'Bu qərar əxlaqi arqumentin hansı tərəfini tutur?', en: 'Which side of moral argument does this take?', ru: 'На чью сторону встаёт решение?' } },
    { id: 'new_equilibrium', order: 19, color: '#2E86C1', colorLight: '#EAF4FB',
      name: { az: 'Yeni Tarazlıq', en: 'New Equilibrium', ru: 'Новое Равновесие' },
      description: { az: 'Yeni dünya qurulur. Köhnə nöqsan aradan qalxır.', en: 'New world built. Old flaw gone.', ru: 'Строится новый мир. Старый изъян устранён.' },
      keyQuestion: { az: 'Yeni tarazlıq köhnəsindən necə fərqlidir?', en: 'How is new equilibrium different?', ru: 'Чем новое равновесие отличается?' } },
    { id: 'thematic_revelation', order: 20, color: '#9B59B6', colorLight: '#F5EEF8',
      name: { az: 'Tematik Açıqlama', en: 'Thematic Revelation', ru: 'Тематическое Откровение' },
      description: { az: 'Filmin əxlaqi arqumenti açıq şəkildə ortaya çıxır.', en: "Film's moral argument openly revealed.", ru: 'Моральный аргумент открыто раскрывается.' },
      keyQuestion: { az: 'Film nəyi doğru, nəyi yanlış göstərir?', en: 'What does the film show as right vs wrong?', ru: 'Что показывает как правильное/неправильное?' } },
    { id: 'audience_catharsis', order: 21, color: '#E67E22', colorLight: '#FEF3E7',
      name: { az: 'Tamaşaçı Katarsisi', en: 'Audience Catharsis', ru: 'Катарсис Аудитории' },
      description: { az: 'Tamaşaçı emosional boşalma yaşayır.', en: 'Audience experiences emotional release.', ru: 'Аудитория переживает эмоциональное освобождение.' },
      keyQuestion: { az: 'Tamaşaçı bu andan sonra nə hiss etməlidir?', en: 'What should the audience feel?', ru: 'Что должна чувствовать аудитория?' } },
    { id: 'world_change', order: 22, color: '#1B4F72', colorLight: '#D6EAF8',
      name: { az: 'Dünyada Dəyişim', en: 'World Change', ru: 'Изменение Мира' },
      description: { az: "Qəhrəmanın dəyişimi dünyanı dəyişdirir.", en: "Hero's change changes the world. Story complete.", ru: 'Изменение героя меняет мир. История завершена.' },
      keyQuestion: { az: 'Şəxsi dəyişim sosial səviyyədə hansı dəyişimi mümkün edir?', en: "What social change does personal change enable?", ru: 'Какое социальное изменение обеспечивает личное?' } },
  ],
};

// ─── 6. EIGHT SEQUENCE ───

export const EIGHT_SEQUENCE: StructureDefinition = {
  id: 'eight_sequence', visualType: 'eight_cols', difficulty: 3,
  filterTags: ['feature', 'thriller', 'drama', 'independent', 'advanced'],
  name: { az: '8 Ardıcıllıq Quruluşu', en: 'Eight Sequence Structure', ru: 'Восьмисекционная Структура' },
  shortDesc: { az: 'Hər ardıcıllıq 10-15 dəqiqəlik mini-filmdir.', en: 'Each sequence is a 10-15 minute mini-film. Most powerful for features.', ru: 'Каждая секция — мини-фильм на 10-15 минут.' },
  fullDesc: { az: 'Uzun metraj üçün ən güclü analiz aracı. Hər ardıcıllığın öz mini-dramı var.', en: 'Most powerful analysis tool for features. Each sequence has its own mini-drama.', ru: 'Мощнейший инструмент анализа. У каждой секции свой мини-сюжет.' },
  bestFor: { az: 'Uzun metraj, triller, drama, bağımsız sinema.', en: 'Feature films, thriller, drama, independent cinema.', ru: 'Полнометражные фильмы, триллер, драма.' },
  filmExamples: [
    { title: 'Parasite', year: 2019, why: '8 ardıcıllıq analizi ən aydın olduğu film' },
    { title: 'No Country for Old Men', year: 2007, why: 'Hər ardıcıllığın öz gərginlik qövründe var' },
    { title: 'Chinatown', year: 1974, why: 'Ardıcıllıq keçişlərindəki dönüşlər klassik nümunədir' },
  ],
  stages: [
    { id: 'seq1', order: 1, color: '#2D2B6B', colorLight: '#EEF0FF',
      name: { az: '1. Ardıcıllıq — Quruluş', en: 'Seq 1 — Establish', ru: 'Секция 1 — Установка' },
      description: { az: 'Dünyanı, qəhrəmanı, tonu tanıtır.', en: 'Introduces world, hero, tone. Main question posed.', ru: 'Представляет мир, героя, тон.' },
      keyQuestion: { az: 'Bu ardıcıllığın mini-dramatik sualı nədir?', en: 'What is the mini-dramatic question?', ru: 'Каков мини-драматический вопрос?' } },
    { id: 'seq2', order: 2, color: '#E67E22', colorLight: '#FEF3E7',
      name: { az: '2. Ardıcıllıq — Tetikleyici', en: 'Seq 2 — Catalyst', ru: 'Секция 2 — Катализатор' },
      description: { az: 'Tetikleyici hadisə. 1. akt sona çatır.', en: 'Catalyst event. Act 1 ends.', ru: 'Событие-катализатор. Акт 1 завершается.' },
      keyQuestion: { az: 'Tetikleyici dünyasını necə dəyişdirir?', en: "How does the catalyst change the hero's world?", ru: 'Как катализатор меняет мир?' } },
    { id: 'seq3', order: 3, color: '#F39C12', colorLight: '#FEF9E7',
      name: { az: '3. Ardıcıllıq — Yeni Dünya', en: 'Seq 3 — New World', ru: 'Секция 3 — Новый Мир' },
      description: { az: 'Qəhrəman yeni dünyaya adaptasiya olur.', en: 'Hero adapts to new world. First successes and failures.', ru: 'Герой адаптируется к новому миру.' },
      keyQuestion: { az: 'Yeni dünyanın qaydaları güclərini zəiflikə çevirirmi?', en: "Do new world rules turn strengths to weaknesses?", ru: 'Превращают ли правила силы в слабости?' } },
    { id: 'seq4', order: 4, color: '#C0392B', colorLight: '#FDEDEC',
      name: { az: '4. Ardıcıllıq — Orta Nöqtəyə', en: 'Seq 4 — Toward Midpoint', ru: 'Секция 4 — К Середине' },
      description: { az: 'Gərginlik artır. İlk böyük uğur ya məğlubiyyət.', en: 'Tension increases. First major success or defeat.', ru: 'Напряжение нарастает. Первый крупный успех/поражение.' },
      keyQuestion: { az: 'Bu sonu orta nöqtəni necə hazırlayır?', en: 'How does this prepare for the midpoint?', ru: 'Как подготавливает среднюю точку?' } },
    { id: 'seq5', order: 5, color: '#8E44AD', colorLight: '#F5EEF8',
      name: { az: '5. Ardıcıllıq — İkinci Yüksəliş', en: 'Seq 5 — Second Rise', ru: 'Секция 5 — Второй Подъём' },
      description: { az: 'Orta nöqtədən sonra. Yeni plan, yeni risklər.', en: 'After midpoint. New plan, new risks.', ru: 'После средней точки. Новый план.' },
      keyQuestion: { az: 'Orta nöqtə strategiyanı necə dəyişdirir?', en: "How does the midpoint change strategy?", ru: 'Как средняя точка меняет стратегию?' } },
    { id: 'seq6', order: 6, color: '#2C3E50', colorLight: '#EAF0FB',
      name: { az: '6. Ardıcıllıq — Parçalanma', en: 'Seq 6 — Falling Apart', ru: 'Секция 6 — Распад' },
      description: { az: 'Hər şey pisləşir. All Is Lost\'a hazırlıq.', en: 'Everything worsens. Preparation for All Is Lost.', ru: 'Всё ухудшается. Подготовка к потере.' },
      keyQuestion: { az: 'Qəhrəmanın imanını nə sınır?', en: "What breaks the hero's faith?", ru: 'Что ломает веру героя?' } },
    { id: 'seq7', order: 7, color: '#D35400', colorLight: '#FBEEE6',
      name: { az: '7. Ardıcıllıq — Final Hazırlığı', en: 'Seq 7 — Final Preparation', ru: 'Секция 7 — Финальная Подготовка' },
      description: { az: 'Dark Night of the Soul. Həll tapılır. 3. akt başlayır.', en: 'Dark Night. Solution found. Act 3 begins.', ru: 'Тёмная ночь души. Решение найдено.' },
      keyQuestion: { az: 'Nə anlayır ki, son mübarizəyə hazır olur?', en: 'What prepares the hero for the final battle?', ru: 'Что готовит героя к финальной битве?' } },
    { id: 'seq8', order: 8, color: '#1B4F72', colorLight: '#D6EAF8',
      name: { az: '8. Ardıcıllıq — Final', en: 'Seq 8 — Finale', ru: 'Секция 8 — Финал' },
      description: { az: 'Son üzləşmə, çevrilim, yeni tarazlıq.', en: 'Final confrontation, transformation, new equilibrium.', ru: 'Финальная конфронтация, трансформация.' },
      keyQuestion: { az: '1. ilə 8. ardıcıllığı müqayisə etsək, dönüşüm görünürmü?', en: 'Comparing seq 1 and 8, is transformation visible?', ru: 'Сравнивая секцию 1 и 8, видна ли трансформация?' } },
  ],
};

// ─── EXPORTS ───

export const STRUCTURE_DEFINITIONS: Record<StructureTypeId, StructureDefinition> = {
  three_act: THREE_ACT,
  save_the_cat: SAVE_THE_CAT,
  dan_harmon: DAN_HARMON,
  vogler: VOGLER,
  john_truby: JOHN_TRUBY,
  eight_sequence: EIGHT_SEQUENCE,
};

export function suggestStructures(tags: string[]): StructureDefinition[] {
  return Object.values(STRUCTURE_DEFINITIONS)
    .filter(s => s.filterTags.some(t => tags.includes(t)))
    .sort((a, b) => a.difficulty - b.difficulty);
}

export const CRITICAL_STAGES: Record<string, string[]> = {
  THREE_ACT:      ['act1', 'midpoint', 'act3'],
  SAVE_THE_CAT:   ['catalyst', 'midpoint', 'all_is_lost', 'finale'],
  DAN_HARMON:     ['you', 'need', 'find', 'change'],
  VOGLER:         ['call_to_adventure', 'ordeal', 'resurrection'],
  JOHN_TRUBY:     ['weakness_need', 'desire', 'opponent', 'self_revelation', 'moral_decision'],
  EIGHT_SEQUENCE: ['seq1', 'seq4', 'seq7', 'seq8'],
};
